"use client";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import "./globals.css";
import { Nav } from "@/common/components/Nav";
import { useConifgApollo } from "@/hooks/useConifgApollo";
import { ContextSessionProvider } from "@/contexts/ContextSessionProvider";
import { useTheme } from "@/hooks/useTheme";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { client, ApolloProvider } = useConifgApollo()
  const {isDarkMode,toggleDarkMode} = useTheme()
  return (
    <html lang="en">
      <body className={isDarkMode ? "bg-primary-dark text-primary-dark" : ""}>
        <ApolloProvider client={client}>
          <SessionProvider>
            <ContextSessionProvider>
              <Nav isDarkMode={isDarkMode} toggleDarkMode={toggleDarkMode}/>
              {children}
            </ContextSessionProvider>
          </SessionProvider>
        </ApolloProvider>
      </body>
    </html>
  );
}
